version: "3.7"
services:
  mysql:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - .:/app
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: